#!/usr/bin/env python3
"""Show the human design-review checklist (Phase 11). Human signoff cannot be
automated or generated by a bot."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from _production_review_common import default_db


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Production-review human checklist (view)")
    ap.add_argument("--review-id", default=None)
    ap.add_argument("--latest", action="store_true")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--db", default=None)
    args = ap.parse_args(argv)

    from engine.production_review.human_checklist import _REQUIRED_ITEMS, CONFIRMATION_TEXT
    from engine.storage import Store
    store = Store(Path(args.db or default_db()))
    rows = store.get_production_human_checklists(50)
    if args.review_id:
        rows = [r for r in rows if r.get("review_id") == args.review_id]
    hc = rows[0] if rows else None
    out = {"required_items": _REQUIRED_ITEMS, "confirmation_text": CONFIRMATION_TEXT,
           "latest_checklist": hc, "note": "Human signoff cannot be generated by a bot/Grok."}
    if args.json:
        print(json.dumps(out, indent=2, default=str))
    else:
        print("Required human-checklist items (manual signoff only):")
        for it in _REQUIRED_ITEMS:
            print(f"  - {it}")
        print(f"latest checklist: {hc.get('status') if hc else 'none'}")
        print("Human signoff cannot be automated or generated by Grok.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
